greeting:
  default:
    user: World

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/cf_spring_rest_development
    username: ${DB_USER:spring-rest}
    password: ${DB_USER_PASSWORD:spring-rest-secret}
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
